### ISSUE TITLE
Create homepage hero

### ISSUE THREAD

**Issue by atomtay** [MAPC/retrofitting-suburbia#12]
- [ ] Insert photo
- [x] Create callout title box
- [x] Overlay first paragraph box

**Comment by atomtay** [comment]
Code-wise this issue is complete, but I'm leaving it open because we need to swap it out with the final photo

**Comment by theryankelly** [comment]
Will use Story Map fullscreen hero styling and image from Google of Dedham Elm St. and Boston Providence Hwy
