### ISSUE TITLE
Darken Building Contrast on Zoom

### ISSUE THREAD

**Issue by theryankelly** [MAPC/retrofitting-suburbia#72]
Editing base map to better show building layers

**Comment by trust-kimberly** [comment]
![Screen Shot 2021-08-25 at 3 52 10 PM](https://user-images.githubusercontent.com/62153141/130855786-e8dcb0bf-3f24-4276-ab9e-4184e4b5c7e9.png)
Buildings layer increases in opacity on zoom, with the above screenshot showing its maximum opacity and coloring. Building numbers also appear on zoom.
